apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVUjRkZysyakNMQ2g4dkNpL2RtSXJOa3p1K1RNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRFl4TnpFMU1UY3dObG9YRFRNegpNRFl4TkRFMU1UY3dObG93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5WFlFcnFnM0Fkam5xS0lsMlVaanNnTE5sazI1ckpxN2NqTm8Ka0tCZFhXci9tSkJ1cW02enpBZk9ZV1hTNGZUT3FzS2o4TitTdDI1eHRjRlcvWjBQeGhhaHZDbDI1Q0Nqa1M5UApPR3RpUnA3MkIxVzhsRjl5Ymp3SldZUCs4MS9aMWVXVXo1UENGRHdMUmV3U2l0ZnViOUE4KzBITDVDaHZhMXl0CklVYkRuNjFvcTNzdVFnMDJsQnZybnEzT3dvQXZuOU5Kb25leklQdkJ3OE1HelcvUGxidGRydzRoWk1RK2VSUVkKNkV4cnY4am9DWENpTkxkeERtY0pvSkxDRG5LNnRWYnhGRHB4cTFXYVEyRUJKT3lUUW1KVDN0YnRpYS83Smk4NApKQ3NYU2dNZWt5blBJUG9pRVVMWUM4ZDdzb0lNUkZTZ1pDbzJOVUhuUENmcHZPWklGd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVUhoMWkrOWxQL0xGTHIwMVJ2M3RxV3lZZnBlc3dId1lEVlIwakJCZ3dGb0FVSGgxaSs5bFAKL0xGTHIwMVJ2M3RxV3lZZnBlc3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBZVNxbnI1RXVza2ZsM1BiYTg4ektIWTZkQ1BsbFFzM2FWYnpjVkVXM1BQWDI0cnZ1VjJPL2N6K1BsVkpYCmJLNWxUMmIzYnJYSlBsaU1VZkNwUEFYTVRXN3VzUEV1OEZoM1lheGxvclBQQStzNUN3UjQ5YzZXOVgwMGJnM2sKdkVMa0prYUxYMkVBM3dNeVV2cHJoYll5ZXNLRUtycGtsYklycHVvY2tkaU8wM1pLSDZnbzB2QUVUd0UvNmFoTApURS8wYWtmbVRndHl2NDBVRXJ4QnZtNmsxR2RqS05ONGs2amRiZnpGUU5JZU13dURxQ21pa2ViL0trNUh1Z3NDCkd1M3Q2Mk5JTGlXbDJRSU5KaDNkZkVlQ0hFTmo1NE1hUm5aMVN4MEFCbUNwL3dWd3lkUmhYODlrSTllSFdrcTQKbG1PQ2lORHNKeXUreDhNV0RzYzQwQU4vdXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://172.31.242.65:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: QVRnMWVtRCtRWWJVbEdpOWxQT0U5ZGdHWHdTSDdMK0p1TlZQZWQwdktQTT0K

